dev_project_id = "dev-ingenius-app-173049"
dev_project_name = "dev-ingenius-app"
dev_tf_state_bucket = "dev-ingenius-app-173049-tf-state"
# prod_project_id = "prod-ingenius-app-759987"
# prod_project_name = "prod-ingenius-app"
# prod_tf_state_bucket = "prod-ingenius-app-759987-tf-state"
